## Part 1: Array Creation & Attributes (The Fundamentals) 

In [3]:
# 1. Import the NumPy library with the alias np.
import numpy as np

In [7]:
# 2. Create a 1D NumPy array from the Python list [1, 2, 3, 4, 5]. 
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [10]:
# 3. Create a 1D array of 10 zeros.
zero = np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
# 4. Create a 3x3 array filled with ones.
ones_arr = np.ones((3,3))
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# 5. Create an array of all even integers from 10 to 50.
even_int = np.arange(10,51,2)
print(even_int)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [17]:
# 6. Create a 3x3 matrix with values ranging from 0 to 8.
matrix = np.arange(9).reshape((3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
# 7. Create a 4x4 identity matrix.
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
# 8. Create an array of 5 numbers evenly spaced between 0 and 1.
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [23]:
# 9. Create a 3x4 array filled with random numbers between 0 and 1.
arr = np.random.rand(3,4)
print(arr)

[[0.20909378 0.510412   0.68557168 0.8146567 ]
 [0.68659366 0.47725407 0.06268606 0.34508705]
 [0.95462121 0.84044771 0.64107879 0.62095325]]


In [26]:
# 10. Create a 5x5 array with random integers from 1 to 100.
arr = np.random.randint(1,101, size=(5,5))
print(arr)

[[41 34 15 51 95]
 [47 27  5 39 12]
 [ 6 24 83 78  6]
 [61 39 67 54 35]
 [40  4 56 27  3]]


In [27]:
# 11. Given the array arr = np.arange(25).reshape(5, 5), find its shape.
arr = np.arange(25).reshape(5, 5)  
arr.shape

(5, 5)

In [28]:
# 12. For the same array arr, find its data type.
arr.dtype

dtype('int64')

In [30]:
# 13. For the same array arr, find the total number of elements. 
arr.size

25

In [32]:
# 14. Create the array [1, 2, 3] but make sure its data type is float. 
arr = np.array([1,2,3], dtype=float)
print(arr)

[1. 2. 3.]


In [33]:
# 15. Convert the data type of an existing integer array to float. 
arr = np.array([1,2,3])
float_arr = arr.astype(float)
print(float_arr)

[1. 2. 3.]


## Part 2: Indexing & Slicing (Accessing Your Data) 

In [79]:
arr_1d = np.arange(10) 
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]]) 

In [36]:
# 16. From arr_1d, get the first element.
arr = arr_1d[0]
print(arr)

0


In [43]:
# 17. From arr_1d, get the last element.
arr = arr_1d[-1]
print(arr)

9


In [44]:
# 18. From arr_1d, get the elements from index 2 up to index 5.
arr = arr_1d[2:6]
print(arr)

[2 3 4 5]


In [45]:
# 19. From arr_1d, get all elements in reverse order. 
arr = arr_1d[::-1]
print(arr)

[9 8 7 6 5 4 3 2 1 0]


In [46]:
# 20. From arr_2d, get the element at row 1, column 2 (which is 6).
arr = arr_2d[1,2]
print(arr)

6


In [47]:
# 21. From arr_2d, get the entire first row [1, 2, 3].
arr = arr_2d[0]
print(arr)

[1 2 3]


In [51]:
# 22. From arr_2d, get the entire second column [2, 5, 8].
arr = arr_2d[:,1]
print(arr)

[2 5 8]


In [54]:
# 23. From arr_2d, extract the sub-array [[1, 2], [4, 5]].
arr = arr_2d[:2,:2]
print(arr)

[[1 2]
 [4 5]]


In [57]:
# 24. Create a boolean mask to find all numbers in arr_1d that are greater than 5.
mask = arr_1d > 5
print(mask)

[False False False False False False  True  True  True  True]


In [58]:
# 25. Use the boolean mask from the previous question to select the actual numbers from arr_1d.
print(arr_1d[mask])

[6 7 8 9]


In [60]:
# 26. In one line, select all numbers from arr_2d that are odd. 
bool_mask = arr_2d % 2 == 1
print(arr_2d[bool_mask])

[1 3 5 7 9]


In [69]:
# 27. In arr_1d, replace all values greater than 5 with the value 0. 
arr_1d[arr_1d > 5] = 0
print(arr_1d)

[0 1 2 3 4 5 0 0 0 0]


In [72]:
# 28. From arr_1d, select the elements at indices 1, 3, and 7. 
arr = arr_1d[[1,3,7]]
print(arr)

[1 3 7]


In [74]:
# 29. From arr_2d, select the first and third rows. 
arr = arr_2d[[0,2]]
print(arr)

[[1 2 3]
 [7 8 9]]


In [80]:
# 30. What is the difference between a slice (view) and a fancy index (copy)? Modify a slice of arr_1d and see if the original changes. 
print(arr_1d)
slice_view = arr_1d[2:5]
slice_view[:] = 0
print(arr_1d)

[0 1 2 3 4 5 6 7 8 9]
[0 1 0 0 0 5 6 7 8 9]


In [82]:
# 31. Create a copy of arr_2d and modify an element in the copy. Check if the original array is affected. 
arr_copy = arr_2d.copy()
arr_copy[0,0] = 10
print(arr_2d)
print(arr_copy)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [85]:
# 32. From arr_2d, get the diagonal elements [1, 5, 9].
arr = np.diag(arr_2d)
print(arr)

[1 5 9]


In [88]:
# 33. Select all rows from arr_2d where the first element is less than 5. 
arr = arr_2d[arr_2d[:,0] < 5]
print(arr)

[[1 2 3]
 [4 5 6]]


In [91]:
# 34. From arr_2d, select the elements [2, 4, 9]. 
arr = arr_2d[[0, 1, 2], [1, 0, 2]] 
print(arr)

[2 4 9]


In [93]:
# 35. Reverse the order of the rows in arr_2d. 
arr = arr_2d[::-1]
print(arr)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


## Part 3: Mathematical & Universal Functions (UFuncs)

In [99]:
a = np.array([1, 2, 3, 4]) 
b = np.array([5, 6, 7, 8]) 

In [101]:
# 36. Add array a and b element-wise.
arr = a + b
print(arr)

[ 6  8 10 12]


In [102]:
# 37. Multiply array a by 3 (scalar multiplication). 
arr = a * 3
print(arr)

[ 3  6  9 12]


In [103]:
# 38. Calculate the square of every element in array a.
arr = np.square(a)
print(arr)

[ 1  4  9 16]


In [105]:
# 39. Calculate the square root of every element in b. 
arr = np.sqrt(b)
print(arr)

[2.23606798 2.44948974 2.64575131 2.82842712]


In [106]:
# 40. Calculate the exponential (e^x) of every element in a.
arr = np.exp(a)
print(arr)

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [107]:
# 41. Find the sum of all elements in a.
arr = a.sum()
print(arr)

10


In [108]:
# 42. Find the mean of all elements in b.
arr = b.mean()
print(arr)

6.5


In [109]:
# 43. Find the maximum value in a.
arr = a.max()
print(arr)

4


In [110]:
# 44. Find the minimum value in b. 
arr = b.min()
print(arr)

5


In [114]:
# 45. Given a 2D array matrix = np.arange(12).reshape(3, 4), find the sum of all its elements.
matrix = np.arange(12).reshape(3,4)
arr = matrix.sum()
print(matrix)
print("Sum = ", arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Sum =  66


In [117]:
# 46. For the matrix, find the sum of each column. 
arr_sum = matrix.sum(axis=0)
print(arr_sum)

[12 15 18 21]


In [118]:
# 47. For the matrix, find the mean of each row. 
arr_mean = matrix.mean(axis=1)
print(arr_mean)

[1.5 5.5 9.5]


In [119]:
# 48. For the matrix, find the minimum value in each row. 
arr_min = matrix.min(axis=1)
print(arr_min)

[0 4 8]


In [120]:
# 49. Create a new array by finding which element is larger at each position between a and b.
large_arr = np.maximum(a,b)
print(large_arr)

[5 6 7 8]


In [121]:
# 50. Round all values in the array arr_float = np.array([1.5, 2.3, 3.8]) to the nearest integer. 
arr_float = np.array([1.5, 2.3, 3.8])
nearest_int = np.round(arr_float)
print(arr_float)
print(nearest_int)

[1.5 2.3 3.8]
[2. 2. 4.]


In [122]:
# 51. Calculate the standard deviation of array a. 
std = np.std(a)
print(std)

1.118033988749895


In [123]:
# 52. Calculate the cumulative sum of a. The result should be [1, 3, 6, 10].
cumsum = np.cumsum(a)
print(cumsum)

[ 1  3  6 10]


In [124]:
# 53. Compare arrays a and b to see if they are equal element-wise.
arr = a == b
print(arr)

[False False False False]


In [125]:
# 54. Check if any element in the result of a > 2 is True. 
arr = np.any(a > 2)
print(arr)

True


In [128]:
# 55. Check if all elements in b are greater than 4. 
arr = np.all(b > 4)
print(arr)

True


## Part 4: Key Manipulation Techniques 

In [130]:
# 56. Reshape the 1D array arr = np.arange(20) into a 4x5 matrix. 
arr = np.arange(20)
matrix = arr.reshape(4,5)
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [133]:
# 57. "Flatten" the 2D array matrix = np.array([[1,2],[3,4]]) into a 1D array.
matrix = np.array([[1,2], [3,4]])
arr = matrix.flatten()
print(arr)

[1 2 3 4]


In [134]:
# 58. What is the main difference between .ravel() and .flatten()?

#.ravel() → returns a view of the original array
#.flatten() → always returns a copy of the array

arr = np.array([[1, 2], [3, 4]])

r = arr.ravel()
f = arr.flatten()

r[0] = 99
print(arr)
f[0] = 100
print(arr)

[[99  2]
 [ 3  4]]
[[99  2]
 [ 3  4]]


In [136]:
# 59. Transpose a 3x5 matrix into a 5x3 matrix.
matrix = np.arange(15).reshape(3, 5)  
print(matrix)

transpose = matrix.T
print(transpose)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [138]:
# 60. Vertically stack the arrays a = np.ones((2,3)) and b = np.zeros((2,3)).
a = np.ones((2,3))
b = np.zeros((2,3))
v_stack = np.vstack((a, b))
print(v_stack)

[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [139]:
# 61. Horizontally stack the arrays a and b.
h_stack = np.hstack((a, b))
print(h_stack)

[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


In [142]:
# 62. Use np.concatenate to achieve the same result as vstack with a and b.
vstack = np.concatenate((a,b), axis=0)
print(vstack)

[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [145]:
# 63. Split the array arr = np.arange(10) into 5 equal sub-arrays. 
arr = np.arange(10)
sub_arr = np.split(arr,5)
print(sub_arr)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [147]:
# 64. Split the 2D array matrix = np.arange(16).reshape(4,4) horizontally into 2 equal arrays.
matrix = np.arange(16).reshape(4,4)
arr = np.hsplit(matrix, 2)
print(arr)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [150]:
# 65. Insert the value 99 at index 2 in the 1D array arr = np.array([1,2,3,4]). 
arr = np.array([1,2,3,4])
new_arr = np.insert(arr, 2, 99)
print(new_arr)

[ 1  2 99  3  4]


In [153]:
# 66. Add the value 5 to the end of array arr.
new_arr = np.append(arr, 5)
print(new_arr)

[1 2 3 4 5]


In [154]:
# 67. Get the unique values from the array arr = np.array([1,1,2,3,3,3,4,5]). 
arr = np.array([1,1,2,3,3,3,4,5])
new_arr = np.unique(arr)
print(new_arr)

[1 2 3 4 5]


In [155]:
# 68. Repeat the array [1,2,3] three times to get [1,2,3,1,2,3,1,2,3]. 
arr = np.array([1,2,3])
new_arr = np.tile(arr, 3)
print(new_arr)

[1 2 3 1 2 3 1 2 3]


In [156]:
# 69. Repeat each element of [1,2,3] three times to get [1,1,1,2,2,2,3,3,3]. 
new_arr = np.repeat(arr, 3)
print(new_arr)

[1 1 1 2 2 2 3 3 3]


In [163]:
# 70. Flip an array horizontally (left to right). 
arr = np.arange(0,9).reshape(3,3)
new_arr = np.fliplr(arr)
print(new_arr)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


## Part 5: Broadcasting & Conditional Logic

In [165]:
# 71. Add a 1D array v = np.array([1, 2, 3]) to each row of a 2D array M = np.ones((4,3)). What is this concept called? 

# this is broadcasting in numpy
v = np.array([1,2,3])
m = np.ones((4,3))
arr = m + v
print(arr)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [168]:
# 72. Can you add a (3,3) matrix and a (3,) vector? If so, how does it work? 

# yes

arr = np.arange(1,10).reshape(3,3)
vec = np.array([10,20,30])
new_arr = vec + arr
print("Array = ",arr)
print("Vector = ",vec)
print("New Array = ",new_arr)

Array =  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector =  [10 20 30]
New Array =  [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [171]:
# 73. Can you add a (3,3) matrix and a (3,1) matrix? 

#yes
matrix1 = np.arange(1,10).reshape(3,3)
matrix2 = np.arange(1,4).reshape(3,1)

arr = matrix1 + matrix2
print(matrix1)
print(matrix2)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [172]:
# 74. Create a 1D array arr = np.arange(10). Use np.where to create a new array where values are 0 if the original value was less than 5, and the original value otherwise.
arr = np.arange(10)
new_arr = np.where(arr < 5, 0, arr)
print(arr)
print(new_arr)

[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 5 6 7 8 9]


In [173]:
# 75. Use np.where to create a new array from arr where even numbers are replaced by 0 and odd numbers by 1.
new_arr = np.where(arr % 2 == 0, 0, 1)

print(arr)
print(new_arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 0 1 0 1 0 1 0 1]


In [178]:
# 76. Create a 5x5 array of random integers. Use np.where to replace all values greater than 50 with the value 50. 
arr = np.random.randint(0,101, (5,5))
new_arr = np.where(arr > 50, 50, arr)
print(arr)
print(new_arr)

[[21 87 46 62 95]
 [31 48 37 70 94]
 [14 38 52 87 62]
 [25 31 63 61 45]
 [50 71  3 43  7]]
[[21 50 46 50 50]
 [31 48 37 50 50]
 [14 38 50 50 50]
 [25 31 50 50 45]
 [50 50  3 43  7]]


In [181]:
# 77. Create a 1D array from 1 to 10. Extract all numbers that are either less than 3 or greater than 8.
arr = np.arange(1,11)
val = arr[(arr < 3) | (arr > 8)]
print(arr)
print(val)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  9 10]


In [183]:
# 78. What will be the result of adding a (4,1) array to a (1,5) array? 
arr1 = np.arange(1,5).reshape(4,1)
arr2 = np.arange(1,6).reshape(1,5)

new_arr = arr1 + arr2
print("(4x1 array)",arr1)
print("(1,5 array)",arr2)
print("New array",new_arr)

(4x1 array) [[1]
 [2]
 [3]
 [4]]
(1,5 array) [[1 2 3 4 5]]
New array [[2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]


In [184]:
# 79. Normalize a 5x5 random matrix (subtract the mean and divide by the standard deviation).

matrix = np.random.randint(0,101, (5,5))
mean = matrix.mean()
std = matrix.std()

normalized_matrix = matrix - mean / std
print(matrix)
print(normalized_matrix)

[[ 50  77  55   4  41]
 [ 93  30  14  36  89]
 [ 11  62  66  12  30]
 [ 92  86  69  73 100]
 [ 44  95  98  43  51]]
[[48.06953936 75.06953936 53.06953936  2.06953936 39.06953936]
 [91.06953936 28.06953936 12.06953936 34.06953936 87.06953936]
 [ 9.06953936 60.06953936 64.06953936 10.06953936 28.06953936]
 [90.06953936 84.06953936 67.06953936 71.06953936 98.06953936]
 [42.06953936 93.06953936 96.06953936 41.06953936 49.06953936]]


In [185]:
# 80. Given a 1D array, create a 2D array where each row is a copy of the original array.
arr = np.array([1, 2, 3, 4])
rows = 5
result = np.tile(arr, (rows, 1))

print(result)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


## Part 6: Statistics, Sorting, & Searching

In [189]:
# 81. Create a 1D array of 10 random integers and sort it in ascending order.
arr = np.random.randint(1,101,10)
sort = np.sort(arr)
print(arr)
print(sort)

[58 72 31 47 74 36 68 50 83  5]
[ 5 31 36 47 50 58 68 72 74 83]


In [191]:
# 82. What is the difference between np.sort(arr) and arr.sort()?
arr = np.array([3, 1, 4, 2])
sorted_arr = np.sort(arr)
print("np.sort", sorted_arr)
print("Original array after np.sort", arr)

arr.sort()
print("arr.sort()", arr)

np.sort [1 2 3 4]
Original array after np.sort [3 1 4 2]
arr.sort() [1 2 3 4]


In [195]:
# 83. Find the indices that would sort the array arr = np.array([3, 1, 4, 2]). 
arr = np.array([3, 1, 4, 2])
indices = np.argsort(arr)
print(indices)

[1 3 0 2]


In [193]:
# 84. Find the index of the maximum value in arr.
index = np.argmax(arr)
print(index)

2


In [197]:
# 85. Find the index of the minimum value in arr. 
min_index = np.argmin(arr)
print(min_index)

1


In [198]:
# 86. In a 2D array, find the index of the maximum value in each column.
arr = np.arange(1,10).reshape(3,3)
max_indices = np.argmax(arr, axis=0)
print(arr)
print(max_indices)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 2 2]


In [199]:
# 87. Find the unique values and their counts in the array arr = np.array([1, 2, 2, 3, 3, 3, 1]).
arr = np.array([1, 2, 2, 3, 3, 3, 1])

unique_values, counts = np.unique(arr, return_counts=True)
print("Unique values", unique_values)
print("Counts", counts)

Unique values [1 2 3]
Counts [2 2 3]


In [200]:
# 88. Find the common elements between two arrays a = np.array([1,2,3]) and b = np.array([2,3,4]).
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

common_elements = np.intersect1d(a, b)
print(common_elements)

[2 3]


In [201]:
# 89. Find the elements in a that are not in b. 
unique_el = np.setdiff1d(a,b)
print(unique_el)

[1]


In [203]:
# 91. Find the 50th percentile (median) of a random array. 
arr = np.random.randint(0, 101, 10)
median = np.median(arr)
print(arr)
print(median)

[69 69 58 36 90 62 23 33 31 57]
57.5


In [204]:
# 92. Find the 25th and 75th percentiles of an array. 
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
p1 = np.percentile(arr, 25)
p2 = np.percentile(arr, 75)

print(p1)
print(p2)

32.5
77.5


In [205]:
# 93. Find all non-zero elements in the array [1, 0, 2, 0, 3].
arr = np.array([1, 0, 2, 0, 3])

indices = np.nonzero(arr)
non_zero_values = arr[indices]
print(indices[0])
print(non_zero_values)

[0 2 4]
[1 2 3]


In [206]:
# 94. Check which elements of array a are present in array b.
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 4, 6])

mask = np.isin(a, b)
common = a[mask]
print(mask)
print(common)

[False  True False  True False]
[2 4]


In [207]:
# 95. Find the top 3 largest values from a 1D array.
arr = np.array([10, 50, 20, 80, 30, 90, 40])

top3 = np.partition(arr, -3)[-3:]
top3_sorted = np.sort(top3)
print(top3_sorted)

[50 80 90]


## Part 7: Practical Applications (Linear Algebra & I/O) 

In [208]:
# 96. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication.
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = np.dot(A, B)
print(C)

[[19 22]
 [43 50]]


In [209]:
# 97. Find the inverse of matrix A. 
A = np.array([[1, 2],
              [3, 4]])

A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [210]:
# 98. Find the determinant of matrix B. 
B = np.array([[5, 6],
              [7, 8]])

det_B = np.linalg.det(B)
print(det_B)

-2.000000000000005


In [214]:
# 99. Save a NumPy array to a binary file named my_array.npy. 
arr = np.array([1, 2, 3, 4, 5])
np.save('my_array.npy', arr)

In [215]:
# 100. Load the array from my_array.npy. 
load_arr = np.load('my_array.npy')

print(load_arr)

[1 2 3 4 5]


In [216]:
# 101. Save a 2D array to a text file my_matrix.csv with comma-separated values.
matrix = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

np.savetxt("my_matrix.csv", matrix, delimiter=",", fmt="%d")

print("Matrix saved to my_matrix.csv")

Matrix saved to my_matrix.csv
